//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collectorz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsServer : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsServer defaultInstance = ((SettingsServer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsServer())));
        
        public static SettingsServer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NumberOfServer {
            get {
                return ((int)(this["NumberOfServer"]));
            }
            set {
                this["NumberOfServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHIRYOUSOOCHI,EIZOUSOOCHI,JOUSETSUSOOCHI")]
        public string ListOfServer {
            get {
                return ((string)(this["ListOfServer"]));
            }
            set {
                this["ListOfServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P,U,V")]
        public string DriveMappingOfServer {
            get {
                return ((string)(this["DriveMappingOfServer"]));
            }
            set {
                this["DriveMappingOfServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNIX\r\n")]
        public string MappingType {
            get {
                return ((string)(this["MappingType"]));
            }
            set {
                this["MappingType"] = value;
            }
        }
    }
}
